config/routes.rb
Banyai5::Application.routes.draw do

    resources :postal_codes

    localized do
      resources :jobs
    end

    post "fbhook" => 'jobs#index'
    match 'allasajanlatok/:id/jelentkezes' => 'jobs#apply', :as => :apply

    get "profile/edit"
    get "profile/step2"
    get "profile/step3"

    put "profile/update"
    put "profile/step2_update"
    put "profile/step3_update"

    mount Ckeditor::Engine => '/ckeditor'

    devise_for :admin_users, ActiveAdmin::Devise.config

    devise_for :applicants, :controllers => { :registrations => "registrations" }

  root :to => 'static#home'

  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|hu/ do
    root :to => 'static#home'

    get '*page' => 'page#show'

  end
end

app/models/job.rb
# -*- encoding : utf-8 -*-
class Job < ActiveRecord::Base
  attr_accessible :branch_id, :city, :company_description, :company_name, :country, :deadline_on,
    :description, :goal, :how_to_apply, :job_category_id, :name, :personal_requirements,
    :position, :responsibilities, :skills, :we_offer, :status, :categorizations_attributes, :language_skills_attributes,
    :publish_on, :expire_on, :management_level_id

  belongs_to :job_category
  belongs_to :branch
  belongs_to :management_level

  has_many :language_skills, :as => :owner
  has_many :categorizations, :as => :owner
  has_many :job_categories, :through => :categorizations
  has_many :job_subcategories, :through => :categorizations

  accepts_nested_attributes_for :language_skills, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :categorizations, :reject_if => :all_blank, :allow_destroy => true

  has_many :signups
  has_many :applicants, :through => :signups

  has_many :scores, :order => 'points DESC'
  has_many :suitable_applicants, :through => :scores,
    :order => 'scores.points DESC', :source => :applicant

  scope :active, lambda { where(:status => 1).
    where("publish_on < ?", Time.now ).
    where("expire_on > ?", Time.now ).
    order("publish_on DESC")  }

  paginates_per 10

  before_save :generate_index
  after_save :recalculate_score


  def self.recent(num=5)
    self.active.order("publish_on DESC").first(num)
  end

  def self.cities
    Job.connection.select_values("SELECT DISTINCT city FROM jobs j
      WHERE j.status = 1 AND j.publish_ON < NOW() AND j.expire_on > NOW()
      ORDER BY city")
  end

  def self.positions
    Job.connection.select_values("SELECT DISTINCT position FROM jobs j
      WHERE j.status = 1 AND j.publish_ON < NOW() AND j.expire_on > NOW()
      ORDER BY position")
  end

  def country_name
    countries = I18nData.countries("HU")
    countries[country.upcase]
  end

  # concat all text fields for poor man's fulltext search
  def all_text
    fields = [name, city, branch.name, description, goal, how_to_apply,
      company_name, company_description, personal_requirements, position, responsibilities,
      skills, we_offer]
    fields.map { |f| ActionController::Base.helpers.strip_tags(f) }.join(" ");
  end

  def allas_kategoria
    categorizations.first.andand.job_subcategory.andand.name
  end

  def uzleti_szegmens
    allas_kategoria
  end

private

  def generate_index
    self.search_index = all_text
  end

  def recalculate_score
    Score.delete_all(:job_id => self.id)
    Applicant.find(:all).each do |a|
      Score.calculate(self, a)
    end
  end

end

app/controllers/jobs_controller.rb
# -*- encoding : utf-8 -*-
class JobsController < ApplicationController

  before_filter :authenticate_applicant!, :only => [:apply]

  def index
    @q = Job.active.search(params[:q])
    @jobs=Job.order('publish_on DESC')
    @jobs = @jobs.page(params[:page])
  end

  def show
    @q = Job.search(params[:q])
    @job = Job.find(params[:id])
  end

  def apply
    @q = Job.search(params[:q])    
    @job = Job.find(params[:id])
    current_applicant.jobs << @job
    current_applicant.save
  end
end

app/helpers/job_helper.rb
# -*- encoding : utf-8 -*-
module JobHelper
end

app/views/jobs/_search_bar.html.erb
      <div class="search_bar">
        <div class="breadcrumb">Állásajánlatok</div>
        <div class="search_box_button">Részletes keresés</div>
      </div><!-- search bar end -->
      <div class="search_box">


      <%= search_form_for q do |f| %>

      <div class="form_group">

        <div class="select_tittle">Állás főkategória</div>

        <div class="search_selector">
        <div class="a1"></div>
        <%= f.select :categorizations_job_category_id_eq,
          options_from_collection_for_select(JobCategory.with_jobs, "id", "name"),
          { :include_blank => true } %>
        </div>

        <div class="select_tittle">Állás kategória</div>
        <div class="search_selector">
          <div class="a2"></div>
          <%= f.select :categorizations_job_subcategory_id_eq,
            options_from_collection_for_select(JobSubcategory.with_jobs, "id", "name"),
          { :include_blank => true }  %>
        </div>

        <div class="select_tittle">Város</div>
        <div class="search_selector">
          <div class="a3"></div>
          <%= f.select :city_eq, options_for_select(Job.cities),
          { :include_blank => true }  %>
        </div>

        <div class="select_tittle">Foglalkozás, beosztás típusa</div>
        <div class="search_selector">
          <div class="a4"></div>
          <%= f.select :management_level_id_eq,
            options_from_collection_for_select(ManagementLevel.with_jobs, "id", "name"),
          { :include_blank => true }  %>
        </div>

      </div>

      <div class="form_group">

        <div class="select_tittle">Pozíció</div>
        <div class="search_selector">
          <div class="a5"></div>
          <%= f.select :position_eq,
            options_for_select(Job.positions),
          { :include_blank => true }  %>
        </div>

        <div class="select_tittle">Nyelv</div>
        <div class="search_selector">
          <div class="a6"></div>
          <%= f.select :language_skills_language_code_eq,
            options_for_select(LanguageSkill.with_jobs),
          { :include_blank => true }  %>
        </div>

      </div>

      <div class="form_group_word">
        <div class="select_tittle">Szabadszavas keresés</div>
        <div class="search_word">
          <%= f.text_field :search_index_cont %>
        </div>
      </div>


      <div class="search_button"><%= submit_tag "Keresés" %></div>



      <% end %>


      </div><!-- search box end -->

app/views/jobs/apply.html.erb
<div class="page_content">
  <div class="text_container">
    <h1>Köszönjük a jelentkezést</h1>

    <p><%= link_to "Vissza", @job %></p>

  </div>
</div>

app/views/jobs/index.html.erb
<div class="page_content">

<% @jobs.each do |job| %>

      <div class="jobs_item">

      <div class="job_list_box">
        <div class="header">Pozíció:</div>
        <div class="title"><%= link_to job.name, job %></div>
        <div class="list_box_left">
          <% unless job.country_name.empty? %>
          <div class="location_header">Munkavégzés helye:</div>
          <div class="location_attr">
            <% unless job.city.empty? %>
              <%= job.city %>,
            <% end %>
            <%= job.country_name %>
          </div>
          <% end%>
          <% unless job.management_level.andand.name.andand.empty? %>
          <div class="management_level_header">Foglalkozás, beosztás típusa:</div>
          <div class="management_level_attr"><%= job.management_level.andand.name %></div>
          <% end %>
          <% unless job.allas_kategoria.andand.empty? %>
          <div class="category_header">Állás kategória:</div>
          <div class="category_attr"><%= job.allas_kategoria %></div>
          <% end %>
        </div>

        <% unless job.deadline_on.nil? %>
        <div class="deadline_header">Jelentkezési határidő:</div>
        <div class="deadline"><%= job.deadline_on %></div>
        <% end %>

        <% unless job.goal.empty? %>
        <div class="description_header">Cél:</div>
        <div class="description">
        <%= job.goal.html_safe %>
        </div>
        <% end %>
      </div><!-- Job list box end -->
      	<div class="right_button"><%= link_to "", job %></div>

      </div><!-- jobs item end -->
<% end %>

<%= paginate @jobs %>
  <div class="jobs_item">
    <div class="job_list_box">
      <a href="http://jooble.co.hu/" target="_blank">
        <img src="/images/jooble.gif" /><br />
        Jooble állásajánlatok</a>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="page_content">

  <div class="job_head">Pozíció</div>
  <div class="job_tittle"><%= @job.name %></div>

  <% unless @job.company_name.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Cég megnevezése</div>
      <div class="attr"><%= @job.company_name %></div>
    </div>
  <% end %>
  <% unless @job.company_description.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Cég bemutatása</div>
      <div class="attr"><%= raw @job.company_description %></div>
    </div>
  <% end %>

  <% unless @job.branch.andand.name.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Tevékenységi ágazat</div>
      <div class="attr"><%= @job.branch.andand.name %></div>
    </div>
  <% end %>

  <% unless @job.position.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Meghirdetett pozíció</div>
      <div class="attr"><%= @job.position %></div>
    </div>
  <% end %>

  <% unless @job.management_level.andand.name.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Foglalkozás, beosztás típusa</div>
      <div class="attr"><%= @job.management_level.andand.name %></div>
    </div>
  <% end %>


  <% unless @job.allas_kategoria.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Állás kategória</div>
      <div class="attr">
        <%= @job.allas_kategoria %>
      </div>
    </div>
  <% end %>

  <% unless @job.country_name.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Hely</div>
      <div class="attr">
        <% unless @job.city.andand.empty? %>
          <%= @job.city %>,
        <% end %>
        <%= @job.country_name %>
      </div>
    </div>
  <% end %>

    <% unless @job.goal.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Cél</div>
      <div class="attr"><%= raw @job.goal %>
      </div>
    </div>
    <% end %>


    <% unless @job.responsibilities.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Fő feladatok/felelősségi körök</div>
      <div class="attr">
        <%= raw @job.responsibilities %>
      </div>
    </div>
    <% end %>

    <% unless @job.skills.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Képzettség/követelmények</div>
      <div class="attr">
        <%= raw @job.skills %>
      </div>
    </div>
    <% end %>



    <% unless @job.personal_requirements.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Személyi elvárások</div>
      <div class="attr">
        <%= raw @job.personal_requirements %>
      </div>
    </div>
    <% end %>

    <% unless @job.we_offer.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Amit mi nyújtunk önnek</div>
      <div class="attr">
        <%= raw @job.we_offer %>
      </div>
    </div>
    <% end %>


    <% unless @job.how_to_apply.andand.empty? %>
    <div class="job_row">
      <div class="job_item">Jelentkezés módja</div>
      <div class="attr"><%= raw @job.how_to_apply %></div>
    </div>
    <% end %>

    <div class="job_application">
      <% if applicant_signed_in? %>
        <% if current_applicant.jobs.include?(@job) %>
          <div class="application_text">Erre az állásra már jelentkezett.</div>
        <% else %>
          <div class="application_button"><%= link_to "Jelentkezem", apply_url(@job.id) %></div>
        <% end %>
      <% else %>
        <div class="application_text">Az állásokra való jelentkezéshez kérjük regisztráljon!
          <%= link_to "Regisztráció »", new_applicant_registration_path %></div>
      <% end %>
    </div>

</div><!-- page content end -->