config/routes.rb
Banyai5::Application.routes.draw do

    resources :postal_codes

    localized do
      resources :jobs
    end

    post "fbhook" => 'jobs#index'
    match 'allasajanlatok/:id/jelentkezes' => 'jobs#apply', :as => :apply

    get "profile/edit"
    get "profile/step2"
    get "profile/step3"

    put "profile/update"
    put "profile/step2_update"
    put "profile/step3_update"

    mount Ckeditor::Engine => '/ckeditor'

    devise_for :admin_users, ActiveAdmin::Devise.config

    devise_for :applicants, :controllers => { :registrations => "registrations" }

  root :to => 'static#home'

  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|hu/ do
    root :to => 'static#home'

    get '*page' => 'page#show'

  end
end

app/views/layouts/application.en.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="hu">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="author" content="Thunderies Ltd." />
  <meta name="publisher" content="Thunderies Ltd." />
  <meta name="distribution" content="global" />
  <meta name="language" content="hu-hu" />
  <meta name="revisit-after" content="7 days" />
  <meta name="keywords" content="Bányai Partners Consulting" />
  <meta name="description" content="Bányai &#38; Partners Consulting" />
  <%= csrf_meta_tags %>

  <title><%= content_for?(:title) ? yield(:title) + " | " : "" %> Bányai &#38; Partners Consulting</title>

  <link rel="icon" type="image/png" href="/images/favicon.png" />

  <link rel="stylesheet" href="/stylesheets/main.css" type="text/css" />
  <link rel="stylesheet" href="/stylesheets/zoli.css" type="text/css" />
  <link rel="stylesheet" href="/stylesheets/modalwindow.css" type="text/css" />


  <%= javascript_include_tag "application" %>
<script type="text/javascript" src="/javascripts/modalwindow.js"></script>
<script type="text/javascript" src="/javascripts/searchtoggle.js"></script>
<script type="text/javascript" src="/javascripts/search_select.js"></script>
<script type="text/javascript" src="/javascripts/jquery.filestyle.js" charset="utf-8"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31430652-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>



</head>
<body>
<div class="page">
	<%= if request.fullpath == ("/")
		  '<div class="container_index">'.html_safe
	  else
		  '<div class="container">'.html_safe
	end %>

    <div class="header">

      <div class="headbar">

        <div class="language-switcher">
          <a href="/" title="magyar">hu</a> | en
        </div>


        <div class="sign_reg">

<% if applicant_signed_in? %>

    <!-- User logged -->
    <%= active_link_to "Profile", profile_edit_path, :class => 'registration' %>
    <%= link_to "Log out", destroy_applicant_session_path, :method => :delete, :class => "logout_link" %>

    <div class="user_logged">Hello <%= link_to current_applicant.name, profile_edit_path %>!</div>

<% else %>

    <%= active_link_to "Registration", new_applicant_registration_path, :class => 'registration' %>
    <a class="login-window" href="#login-box">Log in</a>

<% end %>
        </div><!-- sign n reg -->

        <div id="login-box" class="login-popup">
          <div class="box_head">Log in</div>
          <div class="box_close">
            <a href="#" class="close">Cancel</a>
          </div>

          <div class="modal_content">
     		<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

    			<%= f.input :email, :required => false, :input_html =>{:class => "login_modal"}, :autofocus => true %>
    			<%= f.input :password, :required => false, :input_html =>{:class => "login_modal"} %>
    			<%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
    			<div class="modal_spacer"></div>
    			<%= f.button :submit, "Belépés", :input_html =>{:class => "modal_btn"} %>
    			<%= link_to "Forgot password?", new_password_path(resource_name) %>
    		<% end %>



          </div> <!-- modal content end -->




        </div><!-- login modal end -->

        <div class="social">
	  	  <div class="plusone"><g:plusone style="float: left;" href="https://plus.google.com/115346219421511911198/posts"></g:plusone></div>
          <div class="like">
            <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2FBanyaiConsulting&amp;send=false&amp;layout=button_count&amp;width=150&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:150px; height:21px; padding-top:2px;" allowTransparency="true"></iframe>
          </div><!-- Facebook end -->
          <div class="icon_fb"><a href="http://www.facebook.com/BanyaiConsulting"></a></div>
          <div class="icon_in"><a href="http://www.linkedin.com/company/b-nyai-&-partners-consulting?trk=top_nav_home"></a></div>
          <div class="icon_tw"><a href="https://twitter.com/BanyaiPartners"></a></div>
        </div><!-- social -->

      </div><!-- headbar end -->

    <div class="logo"><a href="/"><img src="/images/logo_banyai.png" alt="logo" /></a><h1>Bányai &#38; Partners Consulting</h1></div><!-- logo -->

    <div class="navigation">
      <ul>
        <li><%= active_link_to "Job offers", "/allasajanlatok" %></li>
        <li><%= active_link_to "Introduction", "/en/introduction" %></li>
        <li><%= active_link_to "Our Services", "/en/services" %></li>
        <li><%= active_link_to "Contacts", "/en/contacts" %></li>
      </ul>
    </div><!-- end navigation -->

    </div><!-- end header -->


    <div class="content">

      <% if flash[:notice] %>
         <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:message] %>
        <p class="message"><%= flash[:message] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
      <% if flash[:error] %>
        <p class="error"><%= flash[:error] %></p>
      <% end %>

      <%= yield %>

    </div><!-- content -->


  </div><!-- end container index -->

</div><!--end page-->



<div class="footer">

  <div class="center_content">
    <div class="newsletter_up">


      <!-- Begin MailChimp Signup Form -->
<link href="http://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup form{background: red;padding:0;}
</style>
<div id="mc_embed_signup">
<form action="http://banyaiconsulting.us5.list-manage.com/subscribe/post?u=85e4b71a3cd0046cd4fd4cdaa&amp;id=014d1e3b63" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	<label class="inside" for="mce-EMAIL">Sign up for our newsletter! »</label>
	<input type="email" value="" name="EMAIL" class="email2" id="mce-EMAIL" placeholder="E-mail address" required>
	<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button2"></div>
</form>
</div>

<!--End mc_embed_signup-->

    </div>

    <div class="footer_contact_text">
    For more information or if you have a question, please, contact us using one of the following addresses or numbers.
    </div>

    <div class="contact_box">
		<div class="contact_head">Contact information</div>
			<div class="description">
				<ul>
					<li>E-mail: <a href="mailto:info@banyaiconsulting.hu?Subject=Információ kérés">info@banyaiconsulting.hu</a></li>
					<li>E-mail: <a href="mailto:palyazat@banyaiconsulting.hu?Subject=Pályázat">palyazat@banyaiconsulting.hu</a></li>
					<li>Telephone: +36 1 950 60 81</li>
				</ul>
			</div>
	</div>

    <div class="contact_box2">
			<div class="contact_head">Our office</div>
			<div class="description">
				Bányai &#38; Partners Consulting Kft.<br />
        Suite 4, 1<sup>st</sup> floor<br />
				44/b. Logodi street<br />
        H-1012 Budapest
				<div class="gmap"><a href="https://goo.gl/maps/N8SFZzQbn8S2">Locate it on the map!</a></div>
			</div>
		</div>

  </div>

</div><!-- end footer -->


<div class="copyright">

	<div class="center_content">
		<img src="/images/logo_footer.png" alt="Bányai &#38; Partners Consulting" />
		<div class="desc">Copyright © 2017 Bányai &#38; Partners Consulting. <a class="privacy-window" href="#privacy_box">Adatvédelmi nyilatkozat</a></div>
		<div id="privacy_box">
		<a href="#" class="close2"></a>
		<h1>Adatvédelmi nyilatkozat</h1><br />
		<p>
		 Ön a regisztrációjával egyidejűleg hozzájárulását adja ahhoz, hogy személyes adatai és önéletrajza a Bányai & Partners Consulting Kft. rendszerében rögzítésre kerüljön. Ugyancsak hozzájárulását adja ahhoz, hogy a rögzítésre került információkat a személyes adatok védelméről szóló 1992. évi LXIII. törvény szerint kezeljük, felhasználjuk, tároljuk és konkrét állásajánlat esetén ügyfeleink részére továbbítsuk vagy hozzáférhetővé tegyük.
					<br /><br />Tájékoztatjuk, hogy személyes adatai kezelésére kizárólag álláskeresés céljából kerül sor. A rendszerben tárolt adatai csak ügyintéző munkatársaink és - amennyiben profilja továbbításra kerül vagy hozzáférhetővé válik - a potenciális munkáltatók részéről eljáró munkatársak számára lesznek hozzáférhetőek. Az adatai kezeléséhez való hozzájáruló nyilatkozatot adatbázisunkból történő kijelentkezéssel bármikor visszavonhatja, ez esetben minden tárolt adatot maradéktalanul eltávolítunk adatbázisunkból.
					<br /><br />Az adatvédelmi törvény rendelkezései alapján a hibásan rögzített vagy időközben módosult adatai helyesbítését kérheti. Felvilágosítást kérhet adatkezelésünkkel kapcsolatban, illetve kérheti adatai törlését. Az adatkezeléssel kapcsolatos jogorvoslati lehetőségekről az adatvédelmi törvény rendelkezik. Az adatbázisba történő regisztrációval egyidejűleg hozzájárulását adja ahhoz, hogy a Bányai & Partners Consulting Kft. állásajánlatokon kívül saját hirdetéseivel, ajánlataival is megkeresse. Amennyiben a jövőben kizárólag állásajánlatokkal kapcsolatos információkat szeretne kapni tőlünk, regisztráció után a profilja beállításainál az ilyen típusú levelezését letilthatja.
		</p>
		</div>
		<div class="impressum">Design &amp; Development:<a href="http://www.pepzen.com/"> <b>Pepzen</b></a></div>
	</div>
</div><!-- end copyright box -->


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="hu">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="author" content="Thunderies Ltd." />
  <meta name="publisher" content="Thunderies Ltd." />
  <meta name="distribution" content="global" />
  <meta name="language" content="hu-hu" />
  <meta name="revisit-after" content="7 days" />
  <meta name="keywords" content="Bányai Partners Consulting" />
  <meta name="description" content="Bányai &#38; Partners Consulting" />
  <%= csrf_meta_tags %>

  <title><%= content_for?(:title) ? yield(:title) + " | " : "" %> Bányai &#38; Partners Consulting</title>

  <link rel="icon" type="image/png" href="/images/favicon.png" />

  <link href="https://plus.google.com/115346219421511911198" rel="publisher">

  <link rel="stylesheet" href="/stylesheets/main.css" type="text/css" />
  <link rel="stylesheet" href="/stylesheets/zoli.css" type="text/css" />
  <link rel="stylesheet" href="/stylesheets/modalwindow.css" type="text/css" />


  <%= javascript_include_tag "application" %>
<script type="text/javascript" src="/javascripts/modalwindow.js"></script>
<script type="text/javascript" src="/javascripts/searchtoggle.js"></script>
<script type="text/javascript" src="/javascripts/search_select.js"></script>
<script type="text/javascript" src="/javascripts/jquery.filestyle.js" charset="utf-8"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31430652-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>



</head>
<body>
<div class="page">
	<%= if request.fullpath == ("/")
		  '<div class="container_index">'.html_safe
	  else
		  '<div class="container">'.html_safe
	end %>

    <div class="header">

      <div class="headbar">

        <div class="language-switcher">
          hu | <a href="/en" title="english">en</a>
        </div>

        <div class="sign_reg">

<% if applicant_signed_in? %>

    <!-- User logged -->
    <%= active_link_to "Profil", profile_edit_path, :class => 'registration' %>
    <%= link_to "Kilépés", destroy_applicant_session_path, :method => :delete, :class => "logout_link" %>

    <div class="user_logged">Üdvözöljük <%= link_to current_applicant.name, profile_edit_path %>!</div>

<% else %>

    <%= active_link_to "Regisztráció", new_applicant_registration_path, :class => 'registration' %>
    <a class="login-window" href="#login-box">Belépés</a>

<% end %>
        </div><!-- sign n reg -->

        <div id="login-box" class="login-popup">
          <div class="box_head">Belépés</div>
          <div class="box_close">
            <a href="#" class="close">Mégsem</a>
          </div>

          <div class="modal_content">
     		<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

    			<%= f.input :email, :required => false, :input_html =>{:class => "login_modal"}, :autofocus => true %>
    			<%= f.input :password, :required => false, :input_html =>{:class => "login_modal"} %>
    			<%= f.input :remember_me, :as => :boolean if devise_mapping.rememberable? %>
    			<div class="modal_spacer"></div>
    			<%= f.button :submit, "Belépés", :input_html =>{:class => "modal_btn"} %>
    			<%= link_to "Elfelejtette jelszavát?", new_password_path(resource_name) %>
    		<% end %>



          </div> <!-- modal content end -->




        </div><!-- login modal end -->

        
        <div class="social">
	  	  <div class="plusone"><g:plusone style="float: left;" href="https://plus.google.com/115346219421511911198/posts"></g:plusone></div>
          <div class="like">
            <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2FBanyaiConsulting&amp;send=false&amp;layout=button_count&amp;width=150&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:150px; height:21px; padding-top:2px;" allowTransparency="true"></iframe>
          </div><!-- Facebook end -->
          <div class="icon_fb"><a href="http://www.facebook.com/BanyaiConsulting"></a></div>
          <div class="icon_in"><a href="http://www.linkedin.com/company/b-nyai-&-partners-consulting?trk=top_nav_home"></a></div>
          <div class="icon_tw"><a href="https://twitter.com/BanyaiPartners"></a></div>
        </div><!-- social -->

      </div><!-- headbar end -->

    <div class="logo"><a href="/"><img src="/images/logo_banyai.png" alt="logo" /></a><h1>Bányai &#38; Partners Consulting</h1></div><!-- logo -->

    <div class="navigation">
      <ul>
        <li><%= active_link_to "Állásajánlatok", "/allasajanlatok" %></li>
        <li><%= active_link_to "Bemutatkozás", "/bemutatkozas" %></li>
        <li><%= active_link_to "Szolgáltatások", "/szolgaltatasok" %></li>
        <li><%= active_link_to "Kapcsolat", "/kapcsolat" %></li>
      </ul>
    </div><!-- end navigation -->

    </div><!-- end header -->


    <div class="content">

      <% if flash[:notice] %>
         <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:message] %>
        <p class="message"><%= flash[:message] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
      <% if flash[:error] %>
        <p class="error"><%= flash[:error] %></p>
      <% end %>

      <%= yield %>

    </div><!-- content -->


  </div><!-- end container index -->

</div><!--end page-->



<div class="footer">

  <div class="center_content">
    <div class="newsletter_up">


      <!-- Begin MailChimp Signup Form -->
<link href="http://cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup form{background: red;padding:0;}
</style>
<div id="mc_embed_signup">
<form action="http://banyaiconsulting.us5.list-manage.com/subscribe/post?u=85e4b71a3cd0046cd4fd4cdaa&amp;id=014d1e3b63" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	<label class="inside" for="mce-EMAIL">Iratkozzon fel hírlevelünkre! »</label>
	<input type="email" value="" name="EMAIL" class="email2" id="mce-EMAIL" placeholder="E-mail cím" required>
	<div class="clear"><input type="submit" value="Feliratkozás" name="subscribe" id="mc-embedded-subscribe" class="button2"></div>
</form>
</div>

<!--End mc_embed_signup-->

    </div>

    <div class="footer_contact_text">
    További információkért, vagy ha kérdése van lépjen velünk kapcsolatba az alábbi elérhetőségek egyikén!
    </div>

    <div class="contact_box">
		<div class="contact_head">Elérhetőség</div>
			<div class="description">
				<ul>
					<li>E-mail: <a href="mailto:info@banyaiconsulting.hu?Subject=Információ kérés">info@banyaiconsulting.hu</a></li>
					<li>E-mail: <a href="mailto:palyazat@banyaiconsulting.hu?Subject=Pályázat">palyazat@banyaiconsulting.hu</a></li>
					<li>Telefon: +36 1 950 60 81</li>
				</ul>
			</div>
	</div>

    <div class="contact_box2">
			<div class="contact_head">Irodánk</div>
			<div class="description">
				Bányai &#38; Partners Consulting Kft.<br />
				 1012 Budapest, Logodi utca 44/b. 1. em. 4
				<div class="gmap"><a href="https://goo.gl/maps/N8SFZzQbn8S2">Nézze meg térképen!</a></div>
			</div>
		</div>

  </div>

</div><!-- end footer -->


<div class="copyright">

	<div class="center_content">
		<img src="/images/logo_footer.png" alt="Bányai &#38; Partners Consulting" />
		<div class="desc">Copyright © 2017 Bányai &#38; Partners Consulting. <a class="privacy-window" href="#privacy_box">Adatvédelmi nyilatkozat</a></div>
		<div id="privacy_box">
		<a href="#" class="close2"></a>
		<h1>Adatvédelmi nyilatkozat</h1><br />
		<p>
		 Ön a regisztrációjával egyidejűleg hozzájárulását adja ahhoz, hogy személyes adatai és önéletrajza a Bányai & Partners Consulting Kft. rendszerében rögzítésre kerüljön. Ugyancsak hozzájárulását adja ahhoz, hogy a rögzítésre került információkat a személyes adatok védelméről szóló 1992. évi LXIII. törvény szerint kezeljük, felhasználjuk, tároljuk és konkrét állásajánlat esetén ügyfeleink részére továbbítsuk vagy hozzáférhetővé tegyük.
					<br /><br />Tájékoztatjuk, hogy személyes adatai kezelésére kizárólag álláskeresés céljából kerül sor. A rendszerben tárolt adatai csak ügyintéző munkatársaink és - amennyiben profilja továbbításra kerül vagy hozzáférhetővé válik - a potenciális munkáltatók részéről eljáró munkatársak számára lesznek hozzáférhetőek. Az adatai kezeléséhez való hozzájáruló nyilatkozatot adatbázisunkból történő kijelentkezéssel bármikor visszavonhatja, ez esetben minden tárolt adatot maradéktalanul eltávolítunk adatbázisunkból.
					<br /><br />Az adatvédelmi törvény rendelkezései alapján a hibásan rögzített vagy időközben módosult adatai helyesbítését kérheti. Felvilágosítást kérhet adatkezelésünkkel kapcsolatban, illetve kérheti adatai törlését. Az adatkezeléssel kapcsolatos jogorvoslati lehetőségekről az adatvédelmi törvény rendelkezik. Az adatbázisba történő regisztrációval egyidejűleg hozzájárulását adja ahhoz, hogy a Bányai & Partners Consulting Kft. állásajánlatokon kívül saját hirdetéseivel, ajánlataival is megkeresse. Amennyiben a jövőben kizárólag állásajánlatokkal kapcsolatos információkat szeretne kapni tőlünk, regisztráció után a profilja beállításainál az ilyen típusú levelezését letilthatja.
		</p>
		</div>
		<div class="impressum">Design &amp; Development:<a href="http://www.pepzen.com/"> <b>Pepzen</b></a></div>
	</div>
</div><!-- end copyright box -->



</body>
</html>

app/views/layouts/basic.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Banyai5</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:message] %>
  <p class="message"><%= flash[:message] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>
<% if flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Banyai5" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= javascript_include_tag "application" %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Banyai5</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>